import dynamic from 'next/dynamic';
import React from 'react';

// Using a fallback for components that might not be default exports, but usually they are.
// If a component is named export, this might throw an error. In that case, we can adjust.
export const ComponentRegistry: Record<string, React.ComponentType<any>> = {
  "AddToCartButton": dynamic(() => import('../components/AddToCartButton')),
  "AddToCartVariant": dynamic(() => import('../components/AddToCartVariant')),
  "AtelierDock": dynamic(() => import('../components/AtelierDock')),
  "AvatarLiquidReveal": dynamic(() => import('../components/AvatarLiquidReveal')),
  "BeakCallout": dynamic(() => import('../components/BeakCallout')),
  "Button3DPushShine": dynamic(() => import('../components/Button3DPushShine')),
  "ButtonShinySparkle": dynamic(() => import('../components/ButtonShinySparkle')),
  "CardCoffeeRoast": dynamic(() => import('../components/CardCoffeeRoast')),
  "CardMagneticCompass": dynamic(() => import('../components/CardMagneticCompass')),
  "CardPhysicalDepthTilt": dynamic(() => import('../components/CardPhysicalDepthTilt')),
  "CardSecureModule": dynamic(() => import('../components/CardSecureModule')),
  "CarouselDepthAccordion": dynamic(() => import('../components/CarouselDepthAccordion')),
  "CleanBorderSocial": dynamic(() => import('../components/CleanBorderSocial')),
  "CobaltDock": dynamic(() => import('../components/CobaltDock')),
  "CompactWeekCalendar": dynamic(() => import('../components/CompactWeekCalendar')),
  "CsvImporter": dynamic(() => import('../components/CsvImporter')),
  "DockGroup": dynamic(() => import('../components/DockGroup')),
  "DynamicAuraDock": dynamic(() => import('../components/DynamicAuraDock')),
  "DynamicCheckbox": dynamic(() => import('../components/DynamicCheckbox')),
  "ExpandableSearch": dynamic(() => import('../components/ExpandableSearch')),
  "ExpandableTagBadge": dynamic(() => import('../components/ExpandableTagBadge')),
  "FAQBloomHub": dynamic(() => import('../components/FAQBloomHub')),
  "FAQDarkArchive": dynamic(() => import('../components/FAQDarkArchive')),
  "FAQPrismSpotlight": dynamic(() => import('../components/FAQPrismSpotlight')),
  "FilterFlyout": dynamic(() => import('../components/FilterFlyout')),
  "FloatingCardUploader": dynamic(() => import('../components/FloatingCardUploader')),
  "FloatingDockFooter": dynamic(() => import('../components/FloatingDockFooter')),
  "FloatingMagneticAccordion": dynamic(() => import('../components/FloatingMagneticAccordion')),
  "FluidActivePagination": dynamic(() => import('../components/FluidActivePagination')),
  "GlowingBorderBadge": dynamic(() => import('../components/GlowingBorderBadge')),
  "HeatmapTestimonial": dynamic(() => import('../components/HeatmapTestimonial')),
  "ImageStackExpansion": dynamic(() => import('../components/ImageStackExpansion')),
  "MinimalDropdown": dynamic(() => import('../components/MinimalDropdown')),
  "MinimalRevealTestimonial": dynamic(() => import('../components/MinimalRevealTestimonial')),
  "NeonBoxPagination": dynamic(() => import('../components/NeonBoxPagination')),
  "OmniShare": dynamic(() => import('../components/OmniShare')),
  "PaginationDemo": dynamic(() => import('../components/PaginationDemo')),
  "ParallaxGridAccordion": dynamic(() => import('../components/ParallaxGridAccordion')),
  "PersonalizedCard": dynamic(() => import('../components/PersonalizedCard')),
  "ProfileMenu": dynamic(() => import('../components/ProfileMenu')),
  "RadialElasticAccordion": dynamic(() => import('../components/RadialElasticAccordion')),
  "RibbonFilter": dynamic(() => import('../components/RibbonFilter')),
  "SpotlightGroupAvatar": dynamic(() => import('../components/SpotlightGroupAvatar')),
  "SwipeOverlayCalendar": dynamic(() => import('../components/SwipeOverlayCalendar')),
  "TabPillIndicator": dynamic(() => import('../components/TabPillIndicator')),
  "TickerBadge": dynamic(() => import('../components/TickerBadge')),
  "TypographicCalendar": dynamic(() => import('../components/TypographicCalendar')),
  "WordSnapCursor": dynamic(() => import('../components/WordSnapCursor')),
  "WorkspacePalette": dynamic(() => import('../components/WorkspacePalette')),
  "ant": dynamic(() => import('../components/ant')),
  "challenge-download-card": dynamic(() => import('../components/challenge-download-card')),
  "crosshair-hover-grid": dynamic(() => import('../components/crosshair-hover-grid')),
  "fluid-command-bar": dynamic(() => import('../components/fluid-command-bar')),
  "fluid-connected-grid": dynamic(() => import('../components/fluid-connected-grid')),
  "fluid-grid-cascade": dynamic(() => import('../components/fluid-grid-cascade')),
  "inpu": dynamic(() => import('../components/inpu')),
  "interactive-3d-book": dynamic(() => import('../components/interactive-3d-book')),
  "minimal-player": dynamic(() => import('../components/minimal-player')),
  "pixelBox": dynamic(() => import('../components/pixelBox')),
  "premium-job-card": dynamic(() => import('../components/premium-job-card')),
  "price-selector": dynamic(() => import('../components/price-selector')),
  "submit-button": dynamic(() => import('../components/submit-button')),
  "sunlight-shine-card": dynamic(() => import('../components/sunlight-shine-card')),
  "timer-setter": dynamic(() => import('../components/timer-setter')),
  "typographic-cube": dynamic(() => import('../components/typographic-cube')),
  "upload-file": dynamic(() => import('../components/upload-file')),
  "vinyl-player": dynamic(() => import('../components/vinyl-player')),
  "wallet-add-cash": dynamic(() => import('../components/wallet-add-cash')),
};

export const componentNames = Object.keys(ComponentRegistry);
